### ISSUE TITLE
Correct browser branding

### ISSUE THREAD

**Issue by PressJump** [focus-browser/browser#67]
There are several hardwritten nightly branding images/text scattered around the browser.
As a result, the browser cannot be rebranded using the configuration files and must be done manually.

This issue has been created for tracking reasons around rebranding nightly.

## Things that are broken
- [ ] MacOS's installer file is put in the wrong location (#36)
- [ ] Windows full installer has nightly images (`engine/browser/branding/*/wiz*.bmp`)
- [ ] Windows 10/11 use nightly images
- [ ] The windows installer puts our code in `Mozilla Developer Preview`
- [x] Browser help branding
- [x] MacOS still uses nightly icons (#81 )
- [x] MacOS still uses `Nightly` name (#81 )
- [x] Default Firefox Bookmarks
- [ ] Private Browsing using Logo Nightly

**Comment by trickypr** [comment]
All changes should be made within gluon's branding generation (`gluon/src/commands/patches/brandingPatch.ts`).

**Comment by trickypr** [comment]
Automation closed this when it shouldn't have

**Comment by PressJump** [comment]
Default Firefox bookmarks are injected into the users profile by default. By default removing them or alternatively It may be a good idea to replace them with a pulse variant that is relative to the features, updates and help pages of pulse browser. Adding it to the list for now.

**Comment by PressJump** [comment]
#114

**Comment by PressJump** [comment]
Nightly branding on new private browsing window (incognito).

**Comment by PressJump** [comment]
New version of Firefox comes with Firefox View which needs a rebranding and removal in some parts of the browser.

**Comment by trickypr** [comment]
I was just going to remove firefox view. From the input I have seen so far, people don't really like it

**Comment by PressJump** [comment]
OS based branding is still Nightly on some systems.

**Comment by splatboydev** [comment]
According to searchfox, “Mozilla Developer Preview” is located in branding/unofficial/branding.nsi, under the brand full name.

![1A4A4050-B9B3-4865-9845-8510761984B6](https://user-images.githubusercontent.com/64037464/210132316-aad9b20e-184f-4680-887b-5be32dc4316a.jpeg)
