### ISSUE TITLE
Mozilla telemetry tracking issue

### ISSUE THREAD

**Issue by trickypr** [focus-browser/browser#84]
This is a big list of all of the Mozilla telemetry that we need to remove at some point.

## General settings
- [ ] `MOZ_TELEMETRY_REPORTING` 
- [ ] `MOZ_SERVICES_HEALTHREPORT`
- [ ] `MOZ_NORMANDY`
- [ ] `MOZ_CRASHREPORTER` (Community input: Is it acceptable to have our own crash reporter endpoint?)

## Potential pitfalls
These are some potential pitfalls that we may have to deal with:
- [ ] When `MOZ_UPDATE_CHANNEL` is set to `beta`, [custom prefs](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/internals/preferences.html) roll out (we will use different names for alpha and stable)

If you have any other potential telemetry points, please let us know and we will add them to this list.
